# aws-sakamoto-test CircleCI 2.0 configuration file
version: 2

jobs:
  # deploy ジョブ: EC2 に SSH 接続して、デプロイを実行する
  deploy:
    docker:
      - image: cimg/base:2022.11
    steps:
      - checkout
      # CircleCI に登録した秘密鍵を呼び出す
      - add_ssh_keys:
          fingerprints:
            - ${FINGER_PRINTS}
      # CircleCI に登録した環境変数を使って SSH
      - run: ssh -v -o StrictHostKeyChecking=no ${USER_NAME}@${HOST_NAME} 'cd /home/ec2-user/prog/coachtech-advance && sudo bash deploy.sh'

workflows:
  version: 2
  # build_and_deploy ジョブ: 一番最初に呼ばれるジョブ
  deploy:
    # deploy ジョブを登録する
    jobs:
      - deploy:
          # main ブランチに push された場合のみ deploy ジョブを実行する
          filters:
            branches:
              only: main
